### ISSUE TITLE
Support for modules?

### ISSUE THREAD

**Issue by nopeless** [hagishi/vscode-ts-debug#12]
Currently `"type": "module"` does not work. Can you add support for this?

**Comment by nopeless** [comment]
I wrote the code for you
```json
// configurations
{
            "name": "ts-node",
            "type": "node",
            "request": "launch",
            "args": [
                "${relativeFile}"
            ],
            "runtimeArgs": [
                "--loader",
                "ts-node/esm"
            ],
// extraneous entries omitted
}
```

**Comment by KevinJin-Coder** [comment]
So..., can we debug somrthing like the following code?
This code compiled into .js file successfully and work as my wish.
I still try to debug this because it is a simple code to try my first typescript debugging.

`import { Student } from './Person';

let s = new Student("Kevin");
s.Introduce();
console.log("ABC");
let a = 1;
console.log(a);`

But I was failed. Maybe I did something wrong, so could someone help me?
Here is what was reported in the console.

`${env:NODE_OPTIONS}=' --require c:/Users/金凯文/.vscode/extensions/ms-vscode.js-debug-nightly-2024.3.417/src/bootloader.js  --inspect-publish-uid=http'; ${env:VSCODE_INSPECTOR_OPTIONS}=':::{"inspectorIpc":"\\\\.\\pipe\\node-cdp.22160-b03ff21a-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"D:\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\金凯文\\AppData\\Local\\Temp\\node-debug-callback-19cb133333375d48"}'; & 'D:\nodejs\node.exe' '-r' 'ts-node/register' 'TypeScript\Main.ts' 
Debugger attached.
(node:21588) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\金凯文\Desktop\TypeScript_VSCodeTest\TypeScript\Main.ts:1
import { Student } from './Person';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module.m._compile (C:\Users\金凯文\Desktop\TypeScript_VSCodeTest\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\金凯文\Desktop\TypeScript_VSCodeTest\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
Waiting for the debugger to disconnect...`
